[pytest]
# Minimum required pytest version
minversion = 8.0

pythonpath = .

# Default command line options for running pytest
# --alluredir=allure-results   -> Saves test results for Allure report generation
# -s                           -> Enables print statements output in the console
# -v                           -> Enables verbose test run logs
addopts = --base-url=https://www.automationexercise.com --alluredir=allure-results -s -v

# Directories to search for test files
testpaths = specs

# Naming patterns for test files, classes, and functions
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Custom test markers registration (prevents PytestUnknownMarkWarning)
markers =
    smoke: Quick smoke tests
    regression: Full regression suite
    flaky: Tests that may fail intermittently
    failed: Tests that are expected to fail